# Generated by Django 4.2.8 on 2025-03-13 14:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit contact number')])),
                ('flat', models.CharField(max_length=50)),
                ('purpose', models.CharField(choices=[('Family/Friend', 'Family/Friend'), ('Delivery', 'Delivery'), ('Maintenance', 'Maintenance'), ('Service', 'Service'), ('Other', 'Other')], max_length=20)),
                ('other_purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitor_photos/')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('is_checked_out', models.BooleanField(default=False)),
                ('action', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
