# Generated by Django 5.1.6 on 2025-03-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0002_apartmentvisitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVerification',
        ),
    ]
