# Generated by Django 4.2.8 on 2025-03-14 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0003_delete_userverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=10, unique=True)),
                ('flat_type', models.CharField(max_length=10)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_contact', models.CharField(max_length=15)),
                ('owner_email', models.EmailField(max_length=254)),
                ('flat_size', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('parking_slots', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='apartmentvisitor',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verify.apartmentflat'),
        ),
    ] 