# Generated by Django 4.2.8 on 2025-03-14 07:36

from django.db import migrations

def create_default_flats(apps, schema_editor):
    ApartmentFlat = apps.get_model('verify', 'ApartmentFlat')
    ApartmentVisitor = apps.get_model('verify', 'ApartmentVisitor')
    
    # Get all unique flat numbers from existing visitors
    flat_numbers = ApartmentVisitor.objects.values_list('flat', flat=True).distinct()
    
    # Create default flat entries for each unique flat number
    for flat_number in flat_numbers:
        ApartmentFlat.objects.create(
            flat_number=flat_number,
            flat_type='1BHK',  # Default value
            owner_name='Default Owner',
            owner_contact='0000000000',
            owner_email='default@example.com',
            flat_size='1000',
            status='Available',
            parking_slots=1,
            password='default_password',
            role='owner'
        )

def reverse_default_flats(apps, schema_editor):
    ApartmentFlat = apps.get_model('verify', 'ApartmentFlat')
    ApartmentFlat.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0004_apartmentflat_alter_apartmentvisitor_flat'),
    ]

    operations = [
        migrations.RunPython(create_default_flats, reverse_default_flats),
    ]
