# Generated by Django 5.1.6 on 2025-03-14 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0005_handle_existing_visitor_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentvisitor',
            name='flat_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartmentflat',
            name='flat_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='apartmentflat',
            name='flat_type',
            field=models.CharField(choices=[('1BHK', '1 BHK'), ('2BHK', '2 BHK'), ('2.5BHK', '2.5 BHK'), ('3BHK', '3 BHK'), ('3.5BHK', '3.5 BHK'), ('4BHK', '4 BHK'), ('Studio', 'Studio')], max_length=10),
        ),
        migrations.AlterField(
            model_name='apartmentflat',
            name='parking_slots',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='apartmentflat',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='apartmentflat',
            name='role',
            field=models.CharField(default='owner', max_length=128),
        ),
        migrations.AlterField(
            model_name='apartmentflat',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=15),
        ),
        migrations.AlterField(
            model_name='apartmentvisitor',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='verify.apartmentflat'),
        ),
    ]
