# Generated by Django 4.2.8 on 2025-03-14 07:36

from django.db import migrations

def insert_sample_flats(apps, schema_editor):
    ApartmentFlat = apps.get_model('verify', 'ApartmentFlat')
    
    # Sample data for different types of flats
    sample_flats = [
        {
            'flat_number': '101',
            'flat_type': '1BHK',
            'owner_name': 'John Doe',
            'owner_contact': '9876543210',
            'owner_email': 'john.doe@example.com',
            'flat_size': '800',
            'status': 'Occupied',
            'parking_slots': 1,
            'password': 'flat101pass',
            'role': 'owner'
        },
        {
            'flat_number': '102',
            'flat_type': '2BHK',
            'owner_name': 'Jane Smith',
            'owner_contact': '9876543211',
            'owner_email': 'jane.smith@example.com',
            'flat_size': '1200',
            'status': 'Occupied',
            'parking_slots': 2,
            'password': 'flat102pass',
            'role': 'owner'
        },
        {
            'flat_number': '201',
            'flat_type': '3BHK',
            'owner_name': 'Robert Johnson',
            'owner_contact': '9876543212',
            'owner_email': 'robert.j@example.com',
            'flat_size': '1500',
            'status': 'Occupied',
            'parking_slots': 2,
            'password': 'flat201pass',
            'role': 'owner'
        },
        {
            'flat_number': '202',
            'flat_type': '2BHK',
            'owner_name': 'Mary Wilson',
            'owner_contact': '9876543213',
            'owner_email': 'mary.w@example.com',
            'flat_size': '1200',
            'status': 'Available',
            'parking_slots': 1,
            'password': 'flat202pass',
            'role': 'owner'
        },
        {
            'flat_number': '301',
            'flat_type': '3BHK',
            'owner_name': 'David Brown',
            'owner_contact': '9876543214',
            'owner_email': 'david.b@example.com',
            'flat_size': '1500',
            'status': 'Occupied',
            'parking_slots': 2,
            'password': 'flat301pass',
            'role': 'owner'
        }
    ]
    
    # Insert the sample data
    for flat_data in sample_flats:
        ApartmentFlat.objects.create(**flat_data)

def remove_sample_flats(apps, schema_editor):
    ApartmentFlat = apps.get_model('verify', 'ApartmentFlat')
    # Remove only the sample flats we created
    ApartmentFlat.objects.filter(flat_number__in=['101', '102', '201', '202', '301']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0005_handle_existing_visitor_data'),
    ]

    operations = [
        migrations.RunPython(insert_sample_flats, remove_sample_flats),
    ] 