# Generated by Django 4.2.8 on 2025-03-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0006_apartmentvisitor_flat_number_and_more'),
        ('verify', '0006_insert_sample_apartment_flats'),
    ]

    operations = [
    ]
