# Generated by Django 5.1.6 on 2025-03-19 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0007_merge_20250314_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentvisitor',
            name='action',
        ),
        migrations.RemoveField(
            model_name='apartmentvisitor',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='apartmentvisitor',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='apartmentvisitor',
            name='flat_number',
        ),
        migrations.RemoveField(
            model_name='apartmentvisitor',
            name='is_checked_out',
        ),
        migrations.RemoveField(
            model_name='apartmentvisitor',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='apartmentvisitor',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='apartmentvisitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmentvisitor',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='apartmentvisitor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apartmentvisitor',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='apartmentvisitor',
            name='flat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='verify.apartmentflat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartmentvisitor',
            name='purpose',
            field=models.CharField(choices=[('Personal', 'Personal Visit'), ('Delivery', 'Delivery'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=20),
        ),
    ]
