# Generated by Django 4.2.8 on 2025-03-19 16:41

from django.db import migrations


def create_default_apartments(apps, schema_editor):
    Apartment = apps.get_model('verify', 'Apartment')
    
    # Create first apartment
    Apartment.objects.create(
        name="Green Valley Heights",
        address="123 Evergreen Street, Greenville, GV 12345",
        total_blocks=3,
        total_flats=120,
        amenities="Swimming Pool, Gym, Community Hall, Children's Play Area, 24/7 Security"
    )
    
    # Create second apartment
    Apartment.objects.create(
        name="Riverside Towers",
        address="456 Riverside Avenue, Riverdale, RD 67890",
        total_blocks=2,
        total_flats=80,
        amenities="Rooftop Garden, Indoor Games, Jogging Track, Pharmacy, Supermarket"
    )
    
    # Create third apartment
    Apartment.objects.create(
        name="Sunnyvale Residency",
        address="789 Sunshine Boulevard, Sunnyvale, SV 54321",
        total_blocks=4,
        total_flats=160,
        amenities="Tennis Court, Basketball Court, Library, Cafe, Spa"
    )


def remove_default_apartments(apps, schema_editor):
    Apartment = apps.get_model('verify', 'Apartment')
    Apartment.objects.filter(name__in=[
        "Green Valley Heights",
        "Riverside Towers", 
        "Sunnyvale Residency"
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0009_apartment_apartmentflat_block_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_apartments, remove_default_apartments),
    ]
