# Generated by Django 4.2.8 on 2025-03-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0011_assign_apartment_to_flats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentflat',
            name='apartment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='verify.apartment'),
            preserve_default=False,
        ),
    ]
