# Generated by Django 4.2.8 on 2025-03-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0012_alter_apartmentflat_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentvisitor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apartmentvisitor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
