# Generated by Django 4.2.8 on 2025-03-19 17:08

from django.db import migrations
from decimal import Decimal

def add_coordinates_to_apartments(apps, schema_editor):
    Apartment = apps.get_model('verify', 'Apartment')
    
    # Sample coordinates for apartments
    coordinates = [
        # Apartment 1 (Green Valley Heights) - random coordinates for Bangalore
        (Decimal('12.9716'), Decimal('77.5946')),
        # Apartment 2 (Riverside Towers) - random coordinates for Mumbai
        (Decimal('19.0760'), Decimal('72.8777')),
        # Apartment 3 (Sunnyvale Residency) - random coordinates for Delhi
        (Decimal('28.7041'), Decimal('77.1025')),
        # Apartment 4 (or any next apartment) - specified coordinates
        (Decimal('16.818585'), Decimal('81.521530'))
    ]
    
    # Get all apartments and assign coordinates
    apartments = Apartment.objects.all().order_by('id')
    
    for i, apartment in enumerate(apartments):
        if i < len(coordinates):
            latitude, longitude = coordinates[i]
            apartment.latitude = latitude
            apartment.longitude = longitude
            apartment.save()
            print(f"Updated coordinates for '{apartment.name}': ({latitude}, {longitude})")
        
        # If there's a 4th apartment specifically, make sure it gets the requested coordinates
        if i == 3:  # 4th apartment (0-indexed)
            lat, lng = Decimal('16.818585'), Decimal('81.521530')
            apartment.latitude = lat
            apartment.longitude = lng
            apartment.save()
            print(f"Set specified coordinates for 4th apartment '{apartment.name}': ({lat}, {lng})")


def remove_coordinates_from_apartments(apps, schema_editor):
    Apartment = apps.get_model('verify', 'Apartment')
    Apartment.objects.all().update(latitude=None, longitude=None)


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0014_apartment_latitude_apartment_longitude'),
    ]

    operations = [
        migrations.RunPython(add_coordinates_to_apartments, remove_coordinates_from_apartments),
    ]
